
# imports
install.packages("pacman")
library(pacman)
pacman::p_load(pacman, dplyr, ggplot2, rio, gridExtra, scales, ggcorrplot, caret, e1071)
```{r}
library(tidyverse)
library(lubridate)
#Load the dataset
adclick <- read.csv("advertising.csv")
adclick <- as.data.frame(adclick)

```

```{r}
#Carrying out Exploratory Data Analysis

#Check the head of the dataset

head(adclick)
```
```{r}
#Check the tail of the dataset
tail(adclick)

```
```{r}
#check the dataframe
class(adclick)
```
```{r}
#Check the length of the datasets
length(adclick)
```
```{r}
#check the  variable types
str(adclick)

```
```{r}
#checking out the variables in the data 
see <- names(adclick)
see
```
```{r}
# checking the summary
summary(adclick)

```
```{r}
# Checking for Missing values
check <- sum(is.na(adclick))
check
#noted that there where no missing values identified
```

```{r}
#Check for the number of duplicates
dups <- sum(duplicated(adclick))
dups
# reported that there were no duplicates found
```

```{r}
#check for uniqueness and consistency
consistent <- unique(adclick)
consistent

```

```{r}
#histogram checking frequency
A_C <- rnorm(n=1000,m=80,sd=20)
hist(A_C,col = "orange")
```


```{r}
#installing ggplot
install.packages("ggplot2")
library(ggplot2)
```

```{r}
#checking the percentage of ad clicks
#prop.table(table(adclick$Clicked.on.Ad))
#this means shows that ourdata is balanced
#there is no form of bias
```
```{r}
#Checking the adclick as per the gender
ggplot(adclick, aes(Male,Clicked.on.Ad )) + geom_bar( stat = "identity") + theme(axis.text.x = element_text(angle = 70, vjust = 0.5, color = "navy")) + xlab("Gender") + ylab("adclicks")+ggtitle("Clicks as per the gender")
#Males reported to have more clicks as compared to female
```
```{r}
#Boxplots
```

```{r}
#Dealing with outliers
#Developing a boxplot for the age
boxplot(adclick$Area.Income,main="boxplot",ylab="male",col=5)
#Outliers where detected in the age column
```

```{r}
# box plot 
boxplot(adclick$Age)
```
```{r}
# box plot 
boxplot(adclick$Area.Income,col = "red")
```
```{r}
# box plot 
boxplot(adclick$Daily.Internet.Usage,col = "brown")
```
```{r}
#Age vs income
ggplot(adclick, aes(Age,Area.Income )) + geom_bar( stat = "identity") +theme(axis.text.x = element_text(angle = 70, vjust = 0.5, color = "navy")) + xlab("Age") + ylab("Area Income")+ggtitle("Age vs Area Income")
# age 31 has the highest Area Income will age 60 has the lowest
```

```{r}
#Visualizing the Age vs Internet usage
ggplot(adclick,color="red", aes(Age,Daily.Internet.Usage),color="red") + geom_bar( stat = "identity") +theme(axis.text.x = element_text(angle = 70, vjust = 0.5, color = "green")) + xlab("Age") + ylab("Daily Internet Usage")+ggtitle("Age vs Internet usage")
#People from ages 27 to 37 reported to be having the most internet usage
```

```{r}
#Viewing the relationship between variables
ggplot(adclick,col="blue",aes(Age,Daily.Time.Spent.on.Site)) +
geom_point() +
theme_minimal() +
labs(title = "Relationship between Age and Gender")
```

```{r}
#Bivariate Analysis
#Comming up with hsitograms to check the distribution
hist(adclick$Age, col="maroon")
# Clearly, there is no relationship between the
```
#Ages ranging between 25 to 40 have the highest number of adclicks, ages(60) reported the lowest adclick

```{r}
hist(adclick$Area.Income, col="brown")
```
# the highest income area Income lyies aboit 55000 and 70000, while the lowest Area Income is about 1000
```{r}

```

```{r}

```
```{r}

```
```{r}

```

```{r}
#ChECKNG CORRELATIONS
cor(cars$speed, cars$dist)
```

```{r}
#corr between age and clicked ad
cor(adclick$Age, adclick$Clicked.on.Ad)
```


```{r}
#corr btw age and Daily Internet Usage
cor(adclick$Age,adclick$Daily.Internet.Usage)
```

```{r}
#install and import cowplot
install.packages("cowplot")
library(cowplot)
```
```{r}
#bivariate
## GGplot
plot1 <- ggplot(adclick, aes(x = Age, y = Daily.Internet.Usage, color = Clicked.on.Ad)) + geom_point(size = 3) +
 theme(text = element_text(size = 10), axis.text.x = element_text(size = 5),axis.text.y = element_text(size = 5))
plot_grid(plot1)
##
##
plot2 <- ggplot(adclick, aes(x = Daily.Time.Spent.on.Site, y=Daily.Internet.Usage, color=Clicked.on.Ad)) + geom_point(size=3)+
 theme(text = element_text(size=10) ,axis.text.x = element_text(size = 5),axis.text.y = element_text(size = 5))
plot_grid(plot2)
##
##
plot3 <- ggplot(adclick, aes(x = Age, y = Area.Income, color=Clicked.on.Ad)) + geom_point(size=3)+
 theme(text = element_text(size=10) ,axis.text.x = element_text(size = 5),axis.text.y = element_text(size = 5))
plot_grid(plot3)
```
```{r}
#Modeling

```